version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1

    steps:
      - checkout
      - run: curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sudo sh -s redis
      - run: sudo apt-get update -qq && sudo apt-get install --no-install-recommends --no-install-suggests -qq redis
      - run: composer update
      - run: composer analyse
      - run: composer lint
      - run: composer test
