version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1
    resource_class: small

    steps:
      - checkout
      - run: sudo apt-get update -qq && sudo apt-get install --no-install-recommends --no-install-suggests -qq redis
      - run: '{ yes "" | sudo pecl install redis; } || true'
      - run: composer update
      - run: composer analyse
      - run: composer lint
      - run: composer test
