version: 2.1

executors:
  php81:
    docker:
      - image: cimg/php:8.1
    resource_class: small
  php82:
    docker:
      - image: cimg/php:8.2
    resource_class: small
  php83:
    docker:
      - image: cimg/php:8.3
    resource_class: small

jobs:
  analyse:
    executor: << parameters.php_executor >>
    parameters:
      php_executor:
        type: string
    steps:
      - checkout
      - run: composer update
      - run: composer analyse
  lint:
    executor: php83
    steps:
      - checkout
      - run: composer update
      - run: composer lint
  test:
    parameters:
      php_executor:
        type: string
    executor: << parameters.php_executor >>
    steps:
      - checkout
      - run: sudo apt-get update -qq && sudo apt-get install --no-install-recommends --no-install-suggests -qq redis
      - run: '{ yes "" | sudo pecl install redis; } || true'
      - run: composer update --prefer-lowest
      - run: composer test
      - run: composer update
      - run: composer test

workflows:
  analyse_lint_test_coverage:
    jobs:
      - analyse:
          matrix:
            parameters:
              php_executor: [php81, php82, php83]
      - lint
      - test:
          matrix:
            parameters:
              php_executor: [php81, php82, php83]
